title: Naveen Reddy Tumu
logo: /assets/img/headshot_circle.png
description: Driven by a passion for innovation, I design efficient data pipelines and cloud-based solutions that empower businesses to make data-driven decisions.
show_downloads: true
theme: jekyll-theme-minimal
