title: Naveen Reddy Tumu
logo: image/J48.PNG
description: Driven by a passion for innovation, I design efficient data pipelines and cloud-based solutions that empower businesses to make data-driven decisions.
show_downloads: true
theme: jekyll-theme-minimal
