title: Naveen Reddy Tumu
logo: /Tumu, Naveen Reddy 2-24.jpg
description: Driven by a passion for innovation, I design efficient data pipelines and cloud-based solutions that empower businesses to make data-driven decisions.
show_downloads: true
theme: jekyll-theme-minimal
